Make script compatible with 'source' instead of ''

diff --git a/aws-session b/aws-session
--- a/aws-session
+++ b/aws-session
@@ -1,13 +1,12 @@
 #!/bin/sh
 
-set -e
-
 echo "Generate and set temporary AWS session tokens for the AWS CLI or other tools." >&2
-echo "To use this script, execute it like this: eval \$(aws-session [options])" >&2
+echo "To use this script, execute it like this: source aws-session [options]" >&2
+echo "If you execute it directly, it will not export AWS_ environment vars into the calling shell." >&2
 echo >&2
 
-which aws >/dev/null || { echo "Required but not installed: aws" >&2; exit 1; }
-which jq >/dev/null || { echo "Required but not installed: jq" >&2; exit 1; }
+which aws >/dev/null || { echo "Required but not installed: aws" >&2; return 1; }
+which jq >/dev/null || { echo "Required but not installed: jq" >&2; return 1; }
 
 # default mode: generate MFA-authenticated session
 mode=mfa
@@ -26,7 +25,6 @@ case "$mode" in
         echo "Using MFA device: ${mfa_device}" >&2
         read -p "Please input MFA token code: " token_code >&2
         aws_session=$(aws sts get-session-token --serial-number "${mfa_device}" --token-code "${token_code}")
-        break
         ;;
     pose)
         if [ "$#" -gt "1" ]; then
@@ -45,14 +43,12 @@ case "$mode" in
         fi
         session_name="assume-account-role-for-cli"
         aws_session=$(aws sts assume-role --role-arn "arn:aws:iam::${account_id}:role/${role_name}" --role-session-name "${session_name}")
-        break
         ;;
     clear)
-        echo "unset AWS_ACCESS_KEY_ID"
-        echo "unset AWS_SECRET_ACCESS_KEY"
-        echo "unset AWS_SESSION_TOKEN"
-        exit 0
-        break
+        unset AWS_ACCESS_KEY_ID
+        unset AWS_SECRET_ACCESS_KEY
+        unset AWS_SESSION_TOKEN
+        return 0
         ;;
     *)
         echo "Usage: $0 [MODE] [OPTIONS]..." >&2
@@ -65,7 +61,7 @@ case "$mode" in
         echo "    ROLE can be a the name of a specific IAM role on the target account. OrganizationAccountAccessRole is used by default." >&2
         echo "aws-session clear" >&2
         echo "    clears the session token, secret key and access key from the environment" >&2
-        exit 1
+        return 1
         ;;
 esac
 
@@ -74,6 +70,6 @@ aws_secret=$(echo "${aws_session}" | jq -r '.Credentials.SecretAccessKey')
 aws_token=$(echo "${aws_session}" | jq -r '.Credentials.SessionToken')
 echo "Temporary access key: ${aws_key} (secret: redacted token: redacted)" >&2
 
-echo "export AWS_ACCESS_KEY_ID=\"${aws_key}\""
-echo "export AWS_SECRET_ACCESS_KEY=\"${aws_secret}\""
-echo "export AWS_SESSION_TOKEN=\"${aws_token}\""
+export AWS_ACCESS_KEY_ID="${aws_key}"
+export AWS_SECRET_ACCESS_KEY="${aws_secret}"
+export AWS_SESSION_TOKEN="${aws_token}"
